FROM node:20 as react-build
WORKDIR /app
COPY package.json yarn.lock ./

ARG SKIP_PREFLIGHT_CHECK
ARG REACT_APP_VERSION
ARG REACT_APP_NAME
ARG REACT_APP_DRIFT_ENABLED

ARG REACT_APP_CLIENT_ID
ARG REACT_APP_SCOPE
ARG REACT_APP_PLACEZ_API_URL
ARG REACT_APP_PAYMENTS_API_URL

ARG REACT_APP_PORTAL
ARG REACT_APP_LOGIN_REDIRECT
ARG REACT_APP_LOGOUT_REDIRECT
ARG REACT_APP_ENVIRONMENT

ARG REACT_APP_INSIGHTS_ENABLED
ARG REACT_APP_INSIGHTS_KEY
ARG REACT_APP_GTAG_MEASUREMENT_ID

ARG REACT_APP_GOOGLE_API_KEY
ARG KENDO_UI_LICENSE


ENV NODE_OPTIONS=--max_old_space_size=4096
ENV VITE_SKIP_PREFLIGHT_CHECK=$SKIP_PREFLIGHT_CHECK

ENV VITE_APP_CLIENT_ID=$REACT_APP_CLIENT_ID
ENV VITE_APP_SCOPE=$REACT_APP_SCOPE
ENV VITE_APP_PLACEZ_API_URL=$REACT_APP_PLACEZ_API_URL
ENV VITE_APP_PAYMENTS_API_URL=$REACT_APP_PAYMENTS_API_URL

ENV VITE_APP_PORTAL=$REACT_APP_PORTAL
ENV VITE_APP_LOGIN_REDIRECT=$REACT_APP_LOGIN_REDIRECT
ENV VITE_APP_LOGOUT_REDIRECT=$REACT_APP_LOGOUT_REDIRECT
ENV VITE_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT

ENV VITE_APP_INSIGHTS_ENABLED=$REACT_APP_INSIGHTS_ENABLED
ENV VITE_APP_INSIGHTS_KEY=$REACT_APP_INSIGHTS_KEY
ENV VITE_APP_GTAG_MEASUREMENT_ID=$REACT_APP_GTAG_MEASUREMENT_ID

ENV VITE_APP_GOOGLE_API_KEY=$REACT_APP_GOOGLE_API_KEY
ENV KENDO_UI_LICENSE=$KENDO_UI_LICENSE

#License
RUN yarn add @progress/kendo-licensing
RUN yarn run kendo-ui-license activate

RUN yarn install
COPY . .
RUN yarn build

# Production environment
FROM nginx:alpine
COPY --from=react-build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf


ARG  SKIP_PREFLIGHT_CHECK
ARG  REACT_APP_CLIENT_ID
ARG  REACT_APP_SCOPE
ARG  REACT_APP_PLACEZ_API_URL
ARG  REACT_APP_PORTAL
ARG  REACT_APP_LOGIN_REDIRECT
ARG  REACT_APP_LOGOUT_REDIRECT
ARG  REACT_APP_ENVIRONMENT
ARG  REACT_APP_INSIGHTS_ENABLED
ARG  REACT_APP_INSIGHTS_KEY
ARG  REACT_APP_GTAG_MEASUREMENT_ID
ARG  REACT_APP_GOOGLE_API_KEY
ARG  KENDO_UI_LICENSE

ENV NODE_OPTIONS=--max_old_space_size=4096
ENV SKIP_PREFLIGHT_CHECK=$SKIP_PREFLIGHT_CHECK
ENV REACT_APP_CLIENT_ID=$REACT_APP_CLIENT_ID
ENV REACT_APP_SCOPE=$REACT_APP_SCOPE
ENV REACT_APP_PLACEZ_API_URL=$REACT_APP_PLACEZ_API_URL
ENV REACT_APP_PORTAL=$REACT_APP_PORTAL
ENV REACT_APP_LOGIN_REDIRECT=$REACT_APP_LOGIN_REDIRECT
ENV REACT_APP_LOGOUT_REDIRECT=$REACT_APP_LOGOUT_REDIRECT
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
ENV REACT_APP_INSIGHTS_ENABLED=$REACT_APP_INSIGHTS_ENABLED
ENV REACT_APP_INSIGHTS_KEY=$REACT_APP_INSIGHTS_KEY
ENV REACT_APP_GTAG_MEASUREMENT_ID=$REACT_APP_GTAG_MEASUREMENT_ID
ENV VITE_APP_GOOGLE_API_KEY=$REACT_APP_GOOGLE_API_KEY
ENV KENDO_UI_LICENSE=$KENDO_UI_LICENSE

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
